language: node_js

node_js:
  - "12.16.3"

dist: trusty

sudo: false

install:
  - npm --version
  - npm i

script:
  - npm run lint
  - npm run test
  - npm run build
  - npm run size

cache:
  directories:
    - node_modules
